### PR TITLE
fixing typos in the french translation

### PR DESCRIPTION
**Pull request by Kelv-vdb**

### CODE REVIEW

**Comment by Girgias** [comment]
Can you rebase on top of master again, I think you got some other changes not covered in #359

**Comment by Corentints** [comment]
There is a small typo error on line 44 🔽 
"Elle contient beaucoup de nouvelle**s** fonctionnalités et d'optimisations, incluant les arguments nommés,"

**Comment by afilina** [comment]
@Kelv-vdb If you need help rebasing, we can set up a call and I can show you how to do it.

**Comment by saundefined** [comment]
Close since the source branch was deleted, and there is no feedback for quite a long time.

**Pull request closed without merging**
