### PR TITLE
Fix: Replace a script with tests

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] replaces a script with tests

Follows https://github.com/php/web-php/issues/579#issuecomment-1168732201.

### CODE REVIEW

**Comment by cmb69** [comment]
Ah, right, thank you! But what about turning this into an actual PHPT test? Basically the same logic and output, but as part of the test suite and not as requestable script.

**Comment by localheinz** [comment]
@cmb69 

Thank you for pointing out, I was not aware this was supposed to be a test!

I split the script into two tests!

**Comment by cmb69** [comment]
Thank you!

**Comment by localheinz** [comment]
Thank you, @cmb69!

**Pull request merged**
