### PR TITLE
Added announcement for PHPConf.Asia 2016

### PR DESCRIPTION
**Pull request by miccheng**

### CODE REVIEW

**Comment by miccheng** [comment]
Hello?

**Comment by bjori** [comment]
@derickr could you look at this one too? It was submitted before the confoo one, so I'm curious why this wasn't reviewed and merged first

**Comment by bjori** [comment]
//cc @Stelian @EliW

**Comment by EliW** [comment]
I don't have merge access here, nor know how things are setup here with the sync'ing between the two repos.    I only know how to commit conferences myself directly into the main repo.   So can't help with a merge request on GitHub.

**Comment by salathe** [comment]
@EliW https://qa.php.net/pulls/#repo=web-php

**Comment by bjori** [comment]
click the "or view command line instructions".
It'll show you have to merge this locally if that is more comfortable.

Another alternative is, if you feel most comfortable creating the entry yourself, is to click "files changed" and copy&paste the values of the xml when you run ./createNewsEntry manually.


I think it is very sad situation we are in now. People that volunteered to help maintaining this section only merge conferences from a very selective group of organizers. Not the smaller conferences that are not directly related to the high profile conferences organized by the same tea party.

**Comment by miccheng** [comment]
@EliW @bjori I have rebased and fixed the merge conflict. Its kinda funny how slow this thing works.

**Comment by EliW** [comment]
I've followed Peter @salathe 's instructions and have merged this.   Thank you Peter for showing me how.  I didn't even know about the qa.php.net website nor it's handy feature of showing you the github pulls and how to merge them.

To Hannes @bjori … Please stop attempting to find conspiracy where there is none.  You constantly assume the worst of us conference organizers.  Versus the reality of us all being overworked, highly-under-paid, and just trying to help everyone out where we can, while being highly fallible humans.  I've always published every conference I can.

In this case, as I stated above, I'd never been shown how to do a github->php.net merge before, and assumed that I didn't have access to do so.  So once requests came in this way, I hadn't paid attention to them waiting for someone else with merge-access to do so.   Now that I know how, I can.   I'd brought this up on the list before, but the fact that the mailing list still 50% of the time decides that anyone on comcast is a spammer and blocks our emails, makes it hard for me to community there.

The really unfortunate part is that the code exists to fully automate this process (via the joind.in integration).  But it keeps not being finalized and pushed up.  Which would 100% clear this whole thing up anyway. :-/

**Comment by bjori** [comment]
Thanks @EliW !

Looking forward to seeing more from you

**Pull request merged**
