### PR TITLE
Use exact word for parameter scroll #74493

### PR DESCRIPTION
**Pull request by JayPHP**
https://bugs.php.net/bug.php?id=74493

### CODE REVIEW

**Comment by morrisonlevi** [comment]
Will you please add a comment in the code that links to the corresponding bug in case the `contains` was intentional? That way when we re-discover why it uses `contains` we can properly fix both.

**Comment by JayPHP** [comment]
@morrisonlevi sure, all done.

**Comment by JayPHP** [comment]
Any chance of getting this merged?

**Comment by peterdd** [comment]
On some pages this does not work: https://www.php.net/manual/en/mysqli.affected-rows.php

Maybe because 'mysql' === '\nmysql' is false..?

Related: https://bugs.php.net/bug.php?id=77036

parameterscroll

**Pull request merged**
