### PR TITLE
Add Japanese translation for PHP 8.3 release page.

### PR DESCRIPTION
**Pull request by NurseAngel**
Add Japanese translation for PHP 8.3 release page.

### CODE REVIEW

**Comment by NurseAngel** [comment]
why  failed?

**Comment by NurseAngel** [comment]
why failed?
Newline?

**Comment by mumumu** [comment]
> why failed? Newline?

@NurseAngel 

Yes, line endings of your file seems to be CRLF (Windows), but this repos use LF only (Unix).

You can fix this by the following command.

```
$ php-cs-fixer fix --ansi --config=.php-cs-fixer.php
```

**Review by mumumu — APPROVED** [review]

**Comment by mumumu** [comment]
Looks good.

@saundefined Can you merge this PR?

**Review by saundefined — APPROVED** [review]
Thanks!

**Pull request merged**
