### PR TITLE
Enhancement: Enable `indentation_type` fixer

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] enables the `indentation_type` fixer
- [x] runs `make coding-standards`

Follows #559.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.4.0/doc/rules/whitespace/indentation_type.rst.

### CODE REVIEW

**Review by cmb69 — APPROVED** [review]
Thank you for the PR! Looks good to me.

I'm fine with using four spaces indent instead of tabs, and generally fine with transitioning to PSR-12 (which is likely one of the most common coding standards for PHP OSS projects).

**Comment by localheinz** [comment]
@cmb69 

I believe that the specifics of a coding standard do not matter as long as they can be enforced automatically!

**Comment by cmb69** [comment]
> I believe that the specifics of a coding standard do not matter as long as they can be enforced automatically!

Right! I should have added: ", so we hopefully all can agree on using PSR-12". I wouldn't want to discuss any single rule individually, but rather get this mess somewhat cleaned up. :)

**Comment by localheinz** [comment]
@cmb69 

As an alternative to enabling fixers individually, I have opened #638!

**Comment by localheinz** [comment]
@cmb69 

Rebased!

**Pull request merged**
