### PR TITLE
Array syntax

### PR DESCRIPTION
**Pull request by MathiasReker**
PHP arrays should be declared using the short syntax.

### CODE REVIEW

**Review by localheinz — COMMENTED** [review]
👍

**Comment by cmb69** [comment]
Besides that this PR has merge conflicts, I really think we should discuss the introduction of a coding standard on the webmaster mailing list.

**Comment by localheinz** [comment]
@cmb69 

I have sent an email on June 17 - not sure if anyone received it or nobody has an interest in discussing it:

CleanShot 2022-06-27 at 15 00 46@2x

**Comment by cmb69** [comment]
Indeed, the [mail went through](https://news-web.php.net/php.webmaster/30092); however, I missed it, and have only yet replied.

**Comment by localheinz** [comment]
@MathiasReker 

Once #559 has been merged, how do you feel about adjusting this pull request here by

- applying this patch

    ```diff
    diff --git a/.php-cs-fixer.php b/.php-cs-fixer.php
    index b2d69e0e..e9bb8e25 100644
    --- a/.php-cs-fixer.php
    +++ b/.php-cs-fixer.php
    @@ -9,6 +9,10 @@ $finder = $config->getFinder()
         ->in(__DIR__)
         ->name(__FILE__);
    
    -$config->setRules([]);
    +$config->setRules([
    +    'array_syntax' => [
    +        'syntax' => 'short',
    +    ],
    +]);
    
    return $config;
    ```

    or this patch

    ```diff
    diff --git a/.php-cs-fixer.php b/.php-cs-fixer.php
    index b2d69e0e..5d466468 100644
    --- a/.php-cs-fixer.php
    +++ b/.php-cs-fixer.php
    @@ -9,6 +9,8 @@ $finder = $config->getFinder()
         ->in(__DIR__)
         ->name(__FILE__);
    
    -$config->setRules([]);
    +$config->setRules([
    +    'array_syntax' => true,
    +]);

    return $config;
    ```
- committing and pushing to fail the build
- running
    
    ```shell
    make coding-standards
    ```
- committing and pushing to fix the build

**Comment by localheinz** [comment]
@cmb69 @MathiasReker 

I have opened https://github.com/php/web-php/pull/659 as a replacement!

**Comment by cmb69** [comment]
I'm closing this, since #659 also adds the respective fixer. Nonetheless, thanks for the PR!

**Pull request closed without merging**
