### PR TITLE
 Replace http:// to https://

### PR DESCRIPTION
**Pull request by dusta**
Change of important links

### CODE REVIEW

**Comment by petk** [comment]
Thanks for this patch. Luckily, I think the PHPeople are now *finally* ready for such changes because I too think that they are really important for 2019: 
https://github.com/php/php-src/pull/3775

Not using (and promoting) https is like living in the past... Thumbs up @dusta 👍

**Comment by petk** [comment]
https://bugs.php.net/bug.php?id=74126

https://bugs.php.net/bug.php?id=67680

https://bugs.php.net/bug.php?id=78137

https://bugs.php.net/bug.php?id=76831

https://bugs.php.net/bug.php?id=78037

:)

**Comment by dusta** [comment]
With this links should not be problems. I have checked and they have forcing redirect to https. There is more in the code http but on php.net is not supported like for example http://docs.php.net so I haven't change that.

**Comment by salathe** [comment]
Thanks for this @dusta! There are a bunch of other php.net sites that look to support HTTPS, would you mind updating references to these as well?

* downloads.php.net
* edit.php.net
* master.php.net
* museum.php.net
* people.php.net
* qa.php.net
* svn.php.net
* windows.php.net

**Comment by dusta** [comment]
svn.php.net is not supported

**Comment by salathe** [comment]
> svn.php.net is not supported

What do you mean by this?

**Comment by dusta** [comment]
> 
> 
> > svn.php.net is not supported
> 
> What do you mean by this?

Interesting... Yesterday https did not work. Can you confirm if everything is alright?

**Comment by salathe** [comment]
> Can you confirm if everything is alright?

I confirm that everything is alright.  😊

**Comment by ramsey** [comment]
Is there anything left to do for this PR (besides resolving the conflicts) before it can be merged?

**Comment by salathe** [comment]
> Is there anything left to do for this PR (besides resolving the conflicts) before it can be merged?

Not that I'm aware of.

@dusta Can you resolve the conflicts on top of current master?  It would also be nice if you could squash the 17 commits into 1 big commit at the same time.

**Comment by dusta** [comment]
@salathe I will try it

**Comment by caugner** [comment]
@salathe Wouldn't it be easier to just `git merge --squash` this branch into master manually or using the GitHub UI?

**Comment by cmb69** [comment]
The merge conflicts have been resolved long ago. :)

**Comment by caugner** [comment]
@cmb69 What exactly is blocking the merge then? :)

**Comment by afilina** [comment]
This PR looks mergeable to me.

**Pull request closed without merging**
