### PR TITLE
Fix: Heredoc syntax

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] fixes heredoc syntax issues

### CODE REVIEW

**Comment by cmb69** [comment]
TIL: https://3v4l.org/8RVCp. Fascinating.

**Comment by cmb69** [comment]
I mean, apparently, having spaces/tabs between the `<<<` and the label is perfectly valid (although undocumented in the PHP manual), so removing this whitespace would be more like a CS fix. However, I can't find a PHP-CS-Fixer fix for this.

**Comment by cmb69** [comment]
Well, let's merge this. I don't think that anybody actually could prefer that notation.

Thank you, @localheinz!

**Comment by localheinz** [comment]
Thank you, @cmb69!

**Pull request merged**
