### PR TITLE
Add PHP Unicorn Conference to conference list

### PR DESCRIPTION
**Pull request by pmeth**

### CODE REVIEW

**Comment by EliW** [comment]
Hey there @pmeth - It's the modus operandi here that you don't make a single conference entry that is BOTH tagged as CFP and Conference.

So two choices for you, to get the most out of your options here:

1. Just update this pull request to remove the 'cfp' tag, and just push it as the conference announcement that 'happens' to have the CfP details in it, or:
2. Update this pull request to just be tagged 'cfp', and just have details about the Call for Papers.  Then after the schedule is complete, make another pull request, tagged 'conference', with your schedule details & full announcement.

Once you decide what you'd prefer there, I'm happy to get it merged quickly.

**Comment by pmeth** [comment]
Oh ok. I was basing this on Madison PHP xml file. I will update.

**Comment by EliW** [comment]
Yeah, sorry @pmeth - Unfortunately Madison was one that was also done incorrectly originally.   You just happened to pick the ONE in the list that wasn't 100% copacetic.

**Comment by EliW** [comment]
Also while you are it it, fixing the merge conflict now caused by my bringing in other commits that were hanging around (sorry), that would be awesome :)

**Comment by pmeth** [comment]
rebased on top of your latest commit, so you shouldn't have any merge issues (if you're quick ;) ).

**Pull request merged**
