### PR TITLE
Enhancement: Enable `random_api_migration` fixer

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] enables the `random_api_migration` fixer
- [x] runs `make coding-standards`

Replaces #545.
Follows #559.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.4.0/doc/rules/alias/random_api_migration.rst.

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, replacing `rand()` with `mt_rand()` is okay (to use the canonical function, not the alias), but wouldn't all these occurrences profit from using `random_int()` instead?

**Comment by localheinz** [comment]
@cmb69 

Looks like it is not possible to seed the generator, see https://stackoverflow.com/q/39352599/1172545.

In other words, the tests would be failing.

We could, however, extract (and thus decouple) a `RandomNumberGenerator` or similar with corresponding implementations. What do you think?

**Comment by TimWolla** [comment]
> Looks like it is not possible to seed the generator when using `ramdon_int()`

Yes, this is by design. 

> We could, however, extract (and thus decouple) a `RandomNumberGenerator` or similar with corresponding implementations. What do you think?

Likely not worth it. Use `random_int()` wherever reasonably possible and then switch to [`\Random\Randomizer`](https://wiki.php.net/rfc/rng_extension) once PHP 8.2 is available to use.

**Comment by localheinz** [comment]
@TimWolla 

> Likely not worth it. Use random_int() wherever reasonably possible and then switch to [\Random\Randomizer](https://wiki.php.net/rfc/rng_extension) once PHP 8.2 is available to use.

Sounds great, but the production system currently runs on PHP 7.3 (maybe), and apparently nobody knows who is responsible for it nor how it could be upgraded to use a current PHP version.

**Comment by TimWolla** [comment]
Yes, that's why I put the "once PHP 8.2 is available to use" there. This was not referring to the gold release in November, but to whenever the requirements for web-php are increased.

Adding a wrapper for the pre-PHP-8.2 RNGs is IMO pure busy work, using the CSPRNG would be great, but if it's painful to do, then it's not worth it just for the anti-spam challenges.

**Comment by morrisonlevi** [comment]
IMO, we can merge this as-is. Is there something _better_? Maybe, but this is a clear improvement that we can merge right this moment, yes?

**Comment by cmb69** [comment]
Oh, indeed, I forgot about the tests. So I agree with @morrisonlevi that this is a step forward. Thank you all!

**Comment by localheinz** [comment]
Thank you, @cmb69, @morrisonlevi, and @TimWolla!

**Pull request merged**
