### PR TITLE
Simplify design. Use bold colors.

### PR DESCRIPTION
**Pull request by Anteste**
I want to simplify the desigb by using bold colors

### CODE REVIEW

**Comment by cmb69** [comment]
@morrisonlevi, since this is about an old commit of you, what do you think?

**Comment by lhsazevedo** [comment]
Adding an screenshot here just so people now what it looks like.
It looks simpler and bolder indeed, but I think the [PHP 8 release page](https://www.php.net/releases/8.0/en.php) style is more in line with the PHP brand.

screenshot

**Comment by samdark** [comment]
I think this one should be closed since, as @lhsazevedo mentioned, current style matches PHP brand way better.

@Anteste thanks anyway.

**Comment by Pythone** [comment]
I think using the color of the year would be good

**Comment by kamil-tekiela** [comment]
It has been 8 years and the design has changed a little bit. The PR is now grossly outdated. It did contain some interesting improvements, but they should be made in a fresh commit. This PR as it is now cannot be merged and reviewing it now doesn't make much sense. If you are still interesting in pursuing these changes, please create a new PR.

**Pull request closed without merging**
