### PR TITLE
Enhancement: Enable `array_syntax` fixer

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] enables the `array_syntax` fixer
- [x] runs `make coding-standards`

Replaces #532.
Follows #559.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.4.0/doc/rules/array_notation/array_syntax.rst.

### CODE REVIEW

**Review by cmb69 — APPROVED** [review]
Thank you! Fine for me, but maybe others prefer the classic `array()` syntax (at least in some cases).

**Comment by localheinz** [comment]
@cmb69 

We could also configure the fixer to use long syntax.

**Comment by cmb69** [comment]
Well, I prefer the short syntax (nowadays for all cases). I just don't want to go ahead and merge, to give others time to object.

**Comment by cmb69** [comment]
Thank you!

**Comment by localheinz** [comment]
Thank you, @cmb69 and @kamil-tekiela!

**Pull request merged**
