### PR TITLE
Added some validation calls for the createNewsEntry

### PR DESCRIPTION
**Pull request by Stelian**
Script now checks if the category is valid on submission.
Script now does a warning based check for the image size to avoid high-res images being pushed.

### CODE REVIEW

**Comment by bjori** [comment]
looks good to me.

One thing that as annoyed over the years is if the markup is not xhtml it'll automatically save it as html, rather then returning "this was html, not xhtml, sure you want to continue? Or would you rather repaste the markup?"

**Comment by Stelian** [comment]
@bjori would treat that in a different pull since that is a bit more broken, in terms of it saves an empty file for invalid html, which is a pain to deal with.

On top of that, I have started a discussion in the emailing list on how to deal with cfp and conference text/date so it might be the case that some extra changes are required.

**Comment by bjori** [comment]
(its not an empty file that gets saved, the <content> element becomes type="html" and tags escaped - we just strongly preferred it to be xhtml).

Feel free to merge this yourself

**Comment by bjori** [comment]
@Stelian seems you never merged this?

**Comment by Stelian** [comment]
@bjori I totally forgot about this PR :) Does it still make sense to merge? Amazingly enough it has 0 conflicts since April

**Comment by salathe** [comment]
Bump. Let's get this merged in, if you want to do the honours?

**Comment by Stelian** [comment]
Hi peter,

I am currently on a ski trip until Monday so that's the earliest I can. If you merge it yourself, would you please change the validation for image to something more sensitive like 250 pix as per previous discussions?

Regards,
Stelian

**Comment by EliW** [comment]
Hey @Stelian - I was looking at potentially merging this myself, but got mentally stuck on the image size discussion.   I think there is a catch-22 here, as if you look at lots of the existing images that are used, a number of conference logos are horizontal in nature.  And restricting to 250x250 disadvantages those.   At the same time. a 400x400 is gigantic.

What if we have a more strict vertical, but allow more horizontal.  Such as 400x250 or 350x250.  I think that would be a good compromise there.

(And I assume that your ski trip is over, so perhaps you can make the change and merge it yourself *grin*)

**Pull request merged**
