### PR TITLE
Update 2017-09-14-1.xml

### PR DESCRIPTION
**Pull request by maverickg59**
Minor spelling change. Just looking out :sunglasses:

### CODE REVIEW

**Comment by maverickg59** [comment]
@remicollet this spelling error exists in all RC postings, would you like me to fix all?

**Comment by maverickg59** [comment]
What❓   👀

**Comment by remicollet** [comment]
Thanks for the notice, fixed in aba5a74d0d3987e16f64b99c6cd284174b6e077f

**Comment by maverickg59** [comment]
You're welcome!

**Pull request closed without merging**
