### PR TITLE
add phpCE CFP announcement

### PR DESCRIPTION
**Pull request by DarGrze**

### CODE REVIEW

**Comment by EliW** [comment]
Hello @DarGrze - Thanks for this submission.  However there appears to be some errors in the XML file.  The ID hash doesn't match the actual file date/name, there is an unescaped & in it, etc.

Did you use the createNewsEntry tool to make this file?  Or did you create it by hand?  If the latter, I'd suggest that you use the bin/createNewsEntry tool to remake it to ensure that it's compliant.

**Comment by DarGrze** [comment]
Hello @EliW,
There's no info about obligatory use of this tool at https://wiki.php.net/conferences – I've choosen editing by hand. But ok, I'll do it once again and open the new request.

**Comment by DarGrze** [comment]
Hi Eli,

This time I entered all my changes according to your suggestions, a few
days ago. I hope it will be complaint with all rules and needs ;)

In case of any complications, please notify me and I'll react ASAP, 'cause
we have a really short time to close our cfp.

Thanks again a lot for your help!


-- Dariusz Grzesista, phpCE.



2017-06-21 19:38 GMT+02:00 Eli White <notifications@github.com>:

**Comment by EliW** [comment]
Thanks @DarGrze DarGrze ... Actually if you read that page it says that there are two options:  1) Use the tool.   2) Email us to add it for you (and we use the tool).

Nowhere does it say 'create XML by hand' :)  Thanks again for the update.  Going to work on merging it now.

**Pull request closed without merging**
