### PR TITLE
Declare strict types

### PR DESCRIPTION
**Pull request by MathiasReker**
Force strict types declaration in all files.

### CODE REVIEW

**Comment by cmb69** [comment]
I wonder *how much* of the functionality that would break.

**Comment by MathiasReker** [comment]
> I wonder _how much_ of the functionality that would break.

No reason to risk any breaking.

**Comment by cmb69** [comment]
I mean, I'm not opposed to declare strict_types, but we would need to make sure that nothing breaks. And unfortunately, we have no tests, as far as I know, nor any static analysis.

**Comment by localheinz** [comment]
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/strict/declare_strict_types.rst.

**Pull request closed without merging**
