### PR TITLE
Change mailing list submit URL to use HTTPS

### PR DESCRIPTION
**Pull request by mikeschinkel**
The mailing list URL "http://main.php.net/entry/subscribe.php" was not using "https://main.php.net/entry/subscribe.php" and thus was failing.

### CODE REVIEW

**Comment by cmb69** [comment]
Thank you!

**Comment by ramsey** [comment]
This is great! Thanks, @mikeschinkel !

**Comment by faizanakram99** [comment]
@mikeschinkel 

Thanks it works, I was able to sign up now. Earlier it threw some error.

I would reply in mailing list where you asked for feedback (read in externals.io) but don't know how to do it.

**Comment by mikeschinkel** [comment]
@faizanakram99 — Excellent. Thank you for the follow up.

> _"I would reply in mailing list where you asked for feedback (read in externals.io) but don't know how to do it."_

 You could just sign up for the _"PHP php.net internal infrastructure discussion"_ list on the mailing list [page you tested](https://www.php.net/mailing-lists.php), and you will get an email asking for confirmation. After you confirm then you would just email the list at php-webmaster@lists.php.net.

**_However_**, no need to email the list about your success now since by commenting here you've already let us know.

**Pull request merged**
