### PR TITLE
feat: include sha256 if available

### PR DESCRIPTION
**Pull request by gsdevme**
Includes the sha256 for the feed & index.php on https://secure.php.net/releases/ 

Unsure on what people would prefer on the styling so any required changes let me know.

### CODE REVIEW

**Comment by gsdevme** [comment]
Hey, anyone got any opinions or recommendations for this PR?

**Comment by gsdevme** [comment]
@dragoonis 👋

**Comment by nevstokes** [comment]
This PR would now appear to be obsolete; sha256 hashes have been included

**Comment by gsdevme** [comment]
Magic. Will leave the PR for fun. 

Sounds like making PRs in GitHub to this repository should be turned off.

**Comment by php-pulls** [comment]
**Comment on behalf of salathe at php.net:**

PR is obsolete.

**Comment by gsdevme** [comment]
@salathe Yeah someone just did the work and committed straight to master 3months after the PR was made to do the exact same bit of work. Im not sure if PHP accept PRs via Github.. who knows.

**Comment by salathe** [comment]
@gsdevme We do accept PR, but for sure we need to be better at pushing through and making sure the PRs get reviewed and resolved (whether merged, or rejected) in a timely manner.

**Comment by gsdevme** [comment]
Thanks for the explanation.

**Pull request closed without merging**
