### PR TITLE
Adding Madison PHP Conference 2017

### PR DESCRIPTION
**Pull request by e3betht**
Adding in a conference and cfp page announcement about Madison PHP Conference 2017.

### CODE REVIEW

**Comment by Stelian** [comment]
@e3betht there seems to be a conflict, can you please merge?

**Comment by Stelian** [comment]
@e3betht ping?

**Comment by e3betht** [comment]
@Stelian I have updated everything so there are no more conflicts. Let me know if you need anything else changed.

**Comment by Stelian** [comment]
@e3betht merged, should be up rather soon.

**Pull request merged**
