### PR TITLE
Add Dutch PHP Conference 2017

### PR DESCRIPTION
**Pull request by pdenooijer**
[Dutch PHP Conference 2017](https://www.phpconference.nl/)

### CODE REVIEW

**Comment by pdenooijer** [comment]
Could you please merge this or comment on this if it has a bug?
@php-pulls

**Comment by pdenooijer** [comment]
This is open for almost a month now. The early bird ticket sale is almost over, so it would be nice to be visible on the php.net website. Could you please merge this? @php-pulls

**Comment by EliW** [comment]
Sorry about that @pdenooijer ... For some reason I never saw the original pull request and notes until today.

**Comment by pdenooijer** [comment]
@EliW thanks 👍 !

**Pull request merged**
