### PR TITLE
No alternative syntax

### PR DESCRIPTION
**Pull request by MathiasReker**
Replace control structure alternative syntax to use braces.

### CODE REVIEW

**Comment by kamil-tekiela** [comment]
Why are you forcing this syntax here? Has this been discussed somewhere?

**Comment by MathiasReker** [comment]
It is better practice. I aim to improve the overall code quality

**Comment by kamil-tekiela** [comment]
> It is better practice. I aim to improve the overall code quality

In what way is it better practice? Please explain. This change doesn't improve code quality IMHO.

**Comment by MathiasReker** [comment]
I get your point of not fixing this in inline HTML.

**Comment by localheinz** [comment]
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/control_structure/no_alternative_syntax.rst.

**Pull request closed without merging**
