### PR TITLE
Update $.scrollTo to last version

### PR DESCRIPTION
**Pull request by lex111**
Fixes the bug [#75458](https://bugs.php.net/bug.php?id=75458)

### CODE REVIEW

**Comment by cmb69** [comment]
If this has actually been tested, I'm +1.

However, php.net still uses jQuery 1.10.2 (released 2013-07-03), so the whole jQuery & plugin stuff should be updated – ideally to supported versions. jQuery 3 drops support for IE 8 and older, though, and since the site is not fully usable without JS (for instance, "Change language" does not work), that might be a problem.

**Comment by lex111** [comment]
> However, php.net still uses jQuery 1.10.2 (released 2013-07-03), so the whole jQuery & plugin stuff should be updated – ideally to supported versions. jQuery 3 drops support for IE 8 and older, though, and since the site is not fully usable without JS (for instance, "Change language" does not work), that might be a problem.

This is not necessary, it is enough to update version of `scrollTo` plugin, it is compatible with the current old version of jQuery, so it will work.

**Comment by lex111** [comment]
Any news?

**Comment by morrisonlevi** [comment]
I now longer have a development server set up to test these changes; can anyone else verify this?

**Comment by salathe** [comment]
@morrisonlevi It Works For Me™

**Comment by morrisonlevi** [comment]
Thanks, @salathe.

**Comment by lex111** [comment]
Hooray! :tada:

**Pull request merged**
