### PR TITLE
Hosting jQuery locally

### LINKED ISSUE #1117: JQuery should not be loaded from external site
Right now, the JQuery library is loaded from an external site (code.jquery.com). Instead, we should self-host this, and place it in the `/cached.php` system: https://github.com/php/web-php/blob/master/include/footer.inc#L99

Previously it was probably on the jquery.com site due to it having a CDN, but we have that ourselves now, there is no reason to not self-host any more (and leak our user's IP addresses).

### PR DESCRIPTION
**Pull request by sy-records**
Close #1117

### CODE REVIEW

**Review by saundefined — APPROVED** [review]
Thanks!

**Comment by dragoonis** [comment]
Hey @saundefined and @sy-records 

What's the rationale behind this ticket ?

When we originally added this via a CDN was because the browser could open multiple sockets via different domains, whereas there is a limit of sockets per domain. 

What has changed? Have you benchmarked the before/after on this? If so what are the results. 

Thanks.

**Comment by cmb69** [comment]
See #1117.

**Comment by dragoonis** [comment]
Thanks @cmb69 I've read that now, and @derick's comments.

What is our CDN now? Cloudfront?

**Comment by jimwins** [comment]
Most/all (working towards all) of the PHP.net web services are fronted by https://www.myrasecurity.com/, which was co-founded by a long-time PHP community member.

**Comment by dragoonis** [comment]
Thanks for replying @jimwins, I read your comment when you originally wrote it, but didn't reply. Cheers 👍

**Pull request merged**
