### PR TITLE
Modernize top half of Thanks page

### PR DESCRIPTION
**Pull request by mvriel**
In issue #682 it was requested to modernize the thanks page; as a first
step in this effort I have given the top half of the page with current
sponsors a brush up, including responsive behaviour.

Unfortunately I could not find a logo for ServerCentral; so I left that
empty.

The improvements in this PR does use CSS Grids, meaning it won't 
show up exactly the same way in IE11 compared to other browsers. 
I have taken this as a given and unfortunate thing, but I do not know
whether this is an issue as I do not know the browserlist.

If the above is an issue, let me know and I'll invest more time on how 
it looks on IE11.

### CODE REVIEW

**Comment by mvriel** [comment]
Desktop

image

Tablet (Portrait)
image

Mobile
image

As for mobile, I am a bit on the fence if the cards aren't too big. Feedback is appreciated, to show it nicely with logo's is a bit of a thing on mobile if you want to keep it small :)

**Comment by heiglandreas** [comment]
I wouldn't worry too much about the size on mobile.

I'm more asking myself whether there is a possibility to randomize an unordered list via CSS. So that not always the same sponsors are "above the fold". Or at the top of the list on mobile.

**Comment by cmb69** [comment]
This looks great! Thank you!

> If the above is an issue, let me know and I'll invest more time on how
> it looks on IE11.

I wouldn't really worry about IE11; I doubt many PHP developers are using that to browse php.net, and even if someone uses IE11, they still get the info.

> I'm more asking myself whether there is a possibility to randomize an unordered list via CSS.

FWIW, that could be done on the server.

**Comment by mvriel** [comment]
> > I'm more asking myself whether there is a possibility to randomize an unordered list via CSS.
> 
> FWIW, that could be done on the server.

Would be a nice followup contribution to keep scope for this PR limited :)

**Comment by RobiNN1** [comment]
> Unfortunately I could not find a logo for ServerCentral; so I left that
empty.

They use it in the favicon so I assume this is their logo.

https://www.servercentral.net/assets/images/mark.svg

mark

I randomly found this PR, and it looks better than current one.

**Comment by samdark** [comment]
👍

**Comment by saundefined** [comment]
Hi all, I resolved the conflict and added the missing logo.

If there are no objections, I'll merge this PR,
if there are comments — I'll try to quickly fix :)

**Review by cmb69 — APPROVED** [review]
Thank you! Looks great!

**Pull request merged**
