### PR TITLE
add DevConf 2016 announcement

### PR DESCRIPTION
**Pull request by tony2001**
Please add the following conf announcement to the calendar

### CODE REVIEW

**Comment by EliW** [comment]
Don't look like the image file was included, nor the updates to archive.xml   Can you commit those changes in @tony2001 ... We need all three files to make an entry.

**Comment by tony2001** [comment]
The image is there: images/news/devconfru2012.png
I'll commit the other file in a moment

**Comment by EliW** [comment]
@tony2001 That last change has merge conflicts.   It looks like instead of using the tool (/bin/createNewsEntry) to make this ... that you did it by hand?

and/or you did it against an older branch that was missing some of the latest updates.   Can you please fix and submit again?

**Comment by tony2001** [comment]
Ok, done

**Comment by tony2001** [comment]
@EliW could you merge it now, plz?

**Comment by EliW** [comment]
Done :)

**Pull request merged**
