### PR TITLE
Single blank line at eof

### PR DESCRIPTION
**Pull request by MathiasReker**
A PHP file without end tag must always end with a single empty line feed.

### CODE REVIEW

**Review by kamil-tekiela — APPROVED** [review]
Looks good but one of your other PRs did the exact opposite. Could you not make a single PR with all the changes and also commit the CS-fixer file?

**Comment by localheinz** [comment]
@kamil-tekiela @MathiasReker 

How do you feel about adding an [`.editorconfig`](https://editorconfig.org)?

```ini
root = true

[*]
insert_final_newline = true

**Review by localheinz — COMMENTED** [review]
👍

**Comment by localheinz** [comment]
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/whitespace/single_blank_line_at_eof.rst.

**Pull request merged**
