### PR TITLE
Announce Bulgaria PHP Conference 2019 CFP

### PR DESCRIPTION
**Pull request by mkosturkov**
Bulgaria PHP Conference 2019 opened their CFP, so it'd be great to have the conference listed under "Conferences calling for papers"

NOTE: There is an entry for the conference already under "Upcoming conferences". I am not sure how the process works, so I did not remove it. If I should, please, reject this PR and let me know that I should, so I can fix the situation and create a new one.

### CODE REVIEW

**Comment by petk** [comment]
I'll check this out soon today... Basically, yes once the conference has been announced duplicate entries should be thought about a bit. Usually conferences have one or two announcements depending on the context - CFP opened and the event announcement. We can adjust this most likely for Bulgaria conference...

**Comment by petk** [comment]
Applied via f68f0093156c61ffb1f90581f129e57564a9fc1c Thanks @mkosturkov 👍

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

Applied.

**Comment by mkosturkov** [comment]
Thanks!

**Pull request closed without merging**
