### PR TITLE
ConFoo 2015 early bird news

### PR DESCRIPTION
**Pull request by afilina**
Here's the fixed paragraph ending.

### CODE REVIEW

**Comment by afilina** [comment]
Sorry, juggling 20 things at once today. Added the content.

**Comment by Stelian** [comment]
No worries, we all have those days. One little thing left, Could you please remove the duplicate ` <div xmlns="http://www.w3.org/1999/xhtml">` and closing div?

**Comment by afilina** [comment]
Done

**Comment by Stelian** [comment]
Thank you, will get the patch and push it.

**Comment by Stelian** [comment]
Hello, I have pushed this into master: http://git.php.net/?p=web/php.git;a=commitdiff;h=ade12f0e157a233833f4ef169365bdfab459cce6

**Comment by php-pulls** [comment]
**Comment on behalf of stelianm at php.net:**

Merged into master.

**Pull request closed without merging**
