### PR TITLE
Add PHP 8.1 key signature for ramsey@php.net

### PR DESCRIPTION
**Pull request by ramsey**

### CODE REVIEW

**Comment by kelunik** [comment]
Could you sign your commit?

**Comment by kelunik** [comment]
Apparently the mobile UI doesn't show the verified badge :-(

**Comment by krakjoe** [comment]
Resolved in 78298f759b19a58b12ea20dde4f6be5b15a96ba2

**Comment by ramsey** [comment]
> Apparently the mobile UI doesn't show the verified badge :-(

No worries. :-)

**Pull request closed without merging**
