### PR TITLE
Enhancement: Enable `ordered_class_elements` fixer

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] enables the `ordered_class_elements` fixer
- [x] excludes `tests/run-tests.php`
- [x] runs `make coding-standards`

Follows #559.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.4.0/doc/rules/class_notation/ordered_class_elements.rst.

### CODE REVIEW

**Comment by cmb69** [comment]
Thank you! This makes sense to me, but I think we should exclude tests/run-tests.php from *all* fixes, since that file is just a copy of php-src/run-tests.php.

**Comment by localheinz** [comment]
@cmb69 

Updated!

**Comment by localheinz** [comment]
@cmb69 

Rebased!

**Comment by cmb69** [comment]
Great! Thank you!

**Comment by localheinz** [comment]
Thank you, @cmb69!

**Pull request merged**
