### PR TITLE
Create id.php to language

### PR DESCRIPTION
**Pull request by rmanalu15**
Add Indonesian language to release page

### CODE REVIEW

**Comment by cmb69** [comment]
This also requires #706.

I'm not sure that it is a good idea to add translations for languages for which we don't have translations of the manual proper (for maintenance reasons).

@saundefined, @pronskiy, what do you think?

**Comment by saundefined** [comment]
Indeed,

Also, this page contains links to document pages with language-specific URLs,
If we merge it, all links to doc pages will look like 404

**Comment by pronskiy** [comment]
+1, I think it's better to stick to the maintained languages.

**Comment by cmb69** [comment]
> I think it's better to stick to the maintained languages

Okay, so I'm closing this and the related #705 and #706.

Nonetheless, thank you for your constribution, @rmanalu15!

**Pull request closed without merging**
