### PR TITLE
Remove safe mode from main feature list

### PR DESCRIPTION
**Pull request by wimg**
Safe mode has been deprecated for a long time. There's no reason it should still be in the list of main features

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, is features.inc even used anywhere?

**Comment by wimg** [comment]
I believe it is here : https://www.php.net/manual/en/

**Comment by cmb69** [comment]
The TOC of the manual is build from the docs sources; e.g. https://www.php.net/manual/de/index.php shows German titles, while features.inc has English titles only. I assume features.inc is a relict from olden days.

**Comment by wimg** [comment]
I fixed it in the right place. I also modified the html (and a small part of the PHP) to make it all more human readable, since it was quite awful, which explains why it was never maintained.
Only did the English version of it though...

**Comment by cmb69** [comment]
I had a closer look, and the code your patching here is only for demo/testing purposes (actually anything in https://github.com/php/web-php/tree/master/manual). What you actually want to do is to modify (or even delete) https://github.com/php/doc-en/blob/master/features/safe-mode.xml (note the different repository), but since the manual is still supposed to document all versions starting from PHP 5.0, this might not be a good idea. Anyhow, feel free to provide a PR against https://github.com/php/doc-en. :)

**Pull request closed without merging**
