### PR TITLE
New with braces

### PR DESCRIPTION
**Pull request by MathiasReker**
All instances created with new keyword must (not) be followed by braces.

### CODE REVIEW

**Comment by kamil-tekiela** [comment]
Unless our coding standard mandates this, I wouldn't change it. It improves nothing.

**Comment by MathiasReker** [comment]
This is the only place that differs.

**Review by localheinz — COMMENTED** [review]
👍

**Comment by cmb69** [comment]
No, we don't have agreed on a CS. That should be discussed on the [PHP php.net internal infrastructure discussion ML](https://www.php.net/mailing-lists.php#internals).

**Comment by localheinz** [comment]
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/operator/new_with_braces.rst.

**Pull request closed without merging**
