### PR TITLE
No alias functions

### PR DESCRIPTION
**Pull request by MathiasReker**
Master functions shall be used instead of aliases.

### CODE REVIEW

**Review by localheinz — COMMENTED** [review]
👍

**Comment by cmb69** [comment]
I think using the canonical function names makes sense. Any particular reason for not doing this @kamil-tekiela?

**Review by kamil-tekiela — APPROVED** [review]
No reason for not doing it. It won't change anything.

**Comment by cmb69** [comment]
> It won't change anything.

It might make the code a little bit easier to grasp for those not used to the aliases. :)

**Comment by tontonsb** [comment]
These (join and sizeof) aliases sometimes improve readability. Similar to how in html `article`, `section` and `main` are functionally [nearly] the same but carry semantics.

**Comment by localheinz** [comment]
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/alias/no_alias_functions.rst.

**Pull request merged**
