### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Credit goes to https://chat.stackoverflow.com/transcript/message/51088407

### CODE REVIEW

**Comment by cmb69** [comment]
Thanks! It would be a good idea to fix this for all available translations.

**Comment by kamil-tekiela** [comment]
> Thanks! It would be a good idea to fix this for all available translations.

Done

**Comment by cmb69** [comment]
Thank you!

**Comment by carusogabriel** [comment]
Wait, wait, wait: why is this a typo? The linked message makes no sense, this is PHP >= 8.0, testing this in a PHP 7 version will break for sure, but not because of the comms, but the missing promotion support. And this is promoting the RFC that allows a trailing comma in a list of parameters

**Comment by cmb69** [comment]
Prior to PHP 8.0.0, trailing commas in parameter definition lists were not allowed, but the PHP 7 example used one.

**Comment by kamil-tekiela** [comment]
> Wait, wait, wait: why is this a typo? The linked message makes no sense, this is PHP >= 8.0, testing this in a PHP 7 version will break for sure, but not because of the comms, but the missing promotion support. And this is promoting the RFC that allows a trailing comma in a list of parameters

On the left-hand side, there are examples of the old way of doing things in PHP 7.4. The trailing comma is only allowed since PHP 8.0 so that example would not work on PHP 7.4. Someone must have made this silly mistake when writing the code and didn't spot the trailing comma which makes this a typo. The code would compile fine under PHP 8.0, but the idea is to show how it worked in PHP 7.4.

**Pull request closed without merging**
