### PR TITLE
Replace references to git.php.net

### PR DESCRIPTION
**Pull request by saundefined**

### CODE REVIEW

**Comment by cmb69** [comment]
Ah, good catch! I wonder whether we should redirect to the raw views, e.g. https://github.com/php/php-src/raw/PHP-7.3/NEWS, instead.

Also, would you mind to add redirects for `php74news` and `php80news`? Obviously, these have been forgotten so far.

**Comment by saundefined** [comment]
@cmb69, thanks! Fixed.

**Review by cmb69 — APPROVED** [review]
Thank you!

Do you have karma to commit yourself?

**Comment by saundefined** [comment]
@cmb69 thank you for the review. 
Committed it 🎉

**Pull request merged**
