### PR TITLE
Add the current PHP logo as the favicon

### PR DESCRIPTION
**Pull request by RiversideRocks**
Just added the current PHP logo as the favicon for consistency.

### CODE REVIEW

**Comment by morrisonlevi** [comment]
As far as I can tell (graphics are not my forte), this is a 32x17 image; that's definitely not a standard size for favicons.  Also, it looks like it has the oval and a white outline, which do not scale down to this size well.

Do you want to try making updated 32x32 and 96x96 versions?

**Comment by RiversideRocks** [comment]
I ran the official php svg through ffmpeg and this is the result:


I looks a bit crushed, so I am going to reduce the height.

**Comment by morrisonlevi** [comment]
I think the "alternative" logo will be better starting point for smaller sizes: https://www.php.net/download-logos.php.

**Comment by RiversideRocks** [comment]
https://www.php.net/images/logos/php-icon.png

This looks quite good in the favicon. Only issue is that it is quite small.

image

Would this work?

**Comment by wh0** [comment]
Do you have a page with that new icon set? I want to test at 1x DPI.

**Comment by RiversideRocks** [comment]
Give this a shot:
https://php-demo-favicon.glitch.me/

**Comment by RiversideRocks** [comment]
This page uses the 32x32 logo from php.net.

**Comment by wh0** [comment]
Thanks. Here's how it looks, for anyone else wondering:

image

**Comment by RiversideRocks** [comment]
Does this work @morrisonlevi?

**Comment by lhsazevedo** [comment]
I know it's been some time since this was proposed, but here is a suggestion using the logo created by @morrisonlevi.
The background blue is #4F5B93, from the PHP 8 release page.

image
image

It looks closer to the current icon, and I find it more readable as well.
If you think it would be good to go ahead with this, let me know and I'll open a PR.

**Comment by lhsazevedo** [comment]
I guess this can be closed now

**Pull request closed without merging**
