### PR TITLE
Fix: Remove useless function

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] removes a useless function `manual_header()`

### CODE REVIEW

**Review by kamil-tekiela — APPROVED** [review]
LGTM I wonder though if it impacts translations.

**Comment by cmb69** [comment]
That would break the manual, since every single manual page calls this function. Note that files under manual/en are just a few examples; the actual files are rendered by PhD, and there we would need to delete this line: https://github.com/php/phd/blob/c3868a838e5029e7cbe39868a1c146e9b81c4986/phpdotnet/phd/Package/PHP/Web.php#L207

After that has been done, and the manual has been successfully rebuilt (happens every 4 or 6 hours), we can merge this PR.

**Comment by kamil-tekiela** [comment]
I thought so. Let's leave it as it is for now.

**Comment by localheinz** [comment]
Thank you, @cmb69 and @kamil-tekiela!

**Pull request merged**
