### PR TITLE
Add CakeFest 2017

### PR DESCRIPTION
**Pull request by dakota**
Adding news item for CakeFest 2017

### CODE REVIEW

**Comment by Stelian** [comment]
Merged in, should be up soon.

**Comment by dakota** [comment]
Thanks 👍

**Comment by Stelian** [comment]
@dakota I just saw that the image is rather big, would it be ok if we resize a bit? Covers most of the news article.

**Comment by dakota** [comment]
I see so too. Sorry about that, you are welcome to resize it to a more manageable size, otherwise I could do it? Thank you.

**Comment by Stelian** [comment]
@dakota, if you could submit a PR with a more balanced size that would be great, I do not want to ruin proportions or resolution or anything related.

**Pull request merged**
