### PR TITLE
added CfP IPC 2016

### PR DESCRIPTION
**Pull request by rmunsky**
Pls add this new entry. i started forking the repo again, was faster.

### CODE REVIEW

**Comment by Stelian** [comment]
Please resolve the conflicts so I can merge this.

**Comment by rmunsky** [comment]
what merge conflicts? i did setup a fresh clone of the repo and comitted  my changes. pls give me some more details. did you change same file meanwhile since my pr was set 11 days ago?

**Comment by Stelian** [comment]
the archive.xml has a conflict, so I am guessing another news item has been added in the meantime, apologies for this.

To reproduce:
```
git fetch git://github.com/php/web-php pull/86/head:pull-request/86
git merge pull-request/86
make test
```

**Comment by rmunsky** [comment]
pls have a look now

**Comment by cbrueckner** [comment]
pls have a look. i added the International PHP Conference Spring 2016 to show this in Upcoming Conferences. Is this fine?

**Comment by php-pulls** [comment]
**Comment on behalf of johannes at php.net:**

merged

**Pull request closed without merging**
