### PR TITLE
Enhancement: Allow copying and pasting commands to set up the local development environment

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] adjusts `README.md` to allow copying and pasting commands to set up the local development environment

### CODE REVIEW

**Review by cmb69 — COMMENTED** [review]
Thank you! Overall this looks like a nice improvement, but I'm not 100% sure about marking the code snippets as `shell` code; after all, these also work on Windows (cmd.exe or even powershell). Maybe just keep it neutral?

**Comment by localheinz** [comment]
@cmb69 

Adjusted!

**Comment by cmb69** [comment]
Thank you!

**Comment by localheinz** [comment]
Thank you, @cmb69!

**Pull request merged**
