### PR TITLE
Announcing PHPBenelux Conference 2017 Call for Papers is open!

### PR DESCRIPTION
**Pull request by DragonBe**
PHPBenelux Conference 2017 is an annual PHP oriented conference in Antwerp, Belgium. We offer two days of stellar tutorials and talks, epic social events and a lineup of the best local and international businesses involved with PHP.

Come and join the fun at https://cfp.phpbenelux.eu/ or visit our conference website https://conference.phpbenelux.eu/2017/ for more information about this event.

Happy PHP-ing,

The PHPBenelux Crew

### CODE REVIEW

**Comment by EliW** [comment]
Hey @DragonBe ... Looks like your Archive.XML is missing the actual announcement body itself.

**Comment by DragonBe** [comment]
Huh? Weird.

In [committed files](https://github.com/php/web-php/pull/123/files) I clearly see the entry in `archive/archive.xml` pointing to the body in `archive/entries/2016-09-06-1.xml` with an image in `images/news/phpbenelux_conference_logo_2017.png`.

What am I missing here?

**Comment by EliW** [comment]
You archive/entries/2016-09-06-1.xml is missing the actual body of the announcement.  IE:  Your <content><div> ... is empty.   See the reference for the recent Scotland announcement for an example: https://github.com/php/web-php/blob/master/archive/entries/2016-08-27-1.xml

**Comment by salathe** [comment]
Can you resize the logo image? We like to keep them around 300 pixels wide.

**Comment by EliW** [comment]
Heh @salathe  ... That's something I would have just done for him after merging it ;)   The content is the part I really wanted him to get right.  But yeah, if you resize it for us, that's awesome too :)

**Comment by DragonBe** [comment]
Oh darn! I was too focused to 👀 it.

Let me fix my wrongdoing immediately + resize the banner size.

**Comment by DragonBe** [comment]
@EliW @salathe: Updated the body text and resized the image into 300px width.

That should be all I guess.

**Comment by EliW** [comment]
Thanks DragonBe ... it looks good.

**Comment by DragonBe** [comment]
Thank you @EliW for the merge 🏆

Me and the @PHPBenelux crew are very grateful. Looking forward receiving your submissions too 😸

**Pull request merged**
