### PR TITLE
Add event PHP Experience 2017 (March, 27-28 - São Paulo, Brazil)

### PR DESCRIPTION
**Pull request by rogeriopradoj**
iMasters PHP Experience 2017 brings together about 1,200 PHP developers in São Paulo, for national and international lectures, workshops, community areas and various networking actions, divided into two days of great content. In 2017 taking place from March 27-28 in São Paulo - Brazil. Curatorship by @phpsp (PHPSP - São Paulo PHP User Group)

### CODE REVIEW

**Comment by Stelian** [comment]
@rogeriopradoj the archive.xml file is conflicting, can you please merge?

**Comment by rogeriopradoj** [comment]
@Stelian Of course!

It's done!

**Comment by Stelian** [comment]
Great, merged into master, will be up soon.

**Comment by rogeriopradoj** [comment]
@Stelian thanks a lot!

Best,

**Pull request merged**
