### PR TITLE
Constant case

### PR DESCRIPTION
**Pull request by MathiasReker**
The PHP constants true, false, and null MUST be written using the correct casing.

### CODE REVIEW

**Comment by cmb69** [comment]
> The PHP constants true, false, and null MUST be written using the correct casing.

RIght. However, the correct casing depends on the coding style.

**Review by localheinz — COMMENTED** [review]
👍

**Comment by localheinz** [comment]
For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/casing/constant_case.rst.

**Comment by cmb69** [comment]
Closing in favor of #660 which just has been merge. Thanks for the PR nonetheless!

**Pull request closed without merging**
